version: '2'

# Services
services:
  # Feed fetcher
  feedfetcher:
    build:
      dockerfile: ./Dockerfile
      context: .
    volumes:
      - ./settings.py:/app/settings.py:ro
      - ./db:/app/db
    restart: unless-stopped
